// Generated by Style Dictionary (`npm run tokens:build`). Do not edit by hand.
// Source of truth: /tokens/*.json — the same tokens the web build consumes.
package dev.aarso.hyle.tokens

import dev.aarso.hyle.Argb

/** Compiled Hyle design tokens, shared with the web and iOS builds. */
object HyleTokens {
    /** ARGB colours (0xAARRGGBB). */
    object Color {
        const val colorPaletteFieldVoid: Argb = 0xFF000000L
        const val colorPaletteFieldNear: Argb = 0xFF0A0809L
        const val colorPaletteFieldRaised: Argb = 0xFF121212L
        const val colorPaletteFieldDeep: Argb = 0xFF050009L
        const val colorPaletteInkPure: Argb = 0xFFECE8E4L
        const val colorPaletteInkFull: Argb = 0xEBECE8E4L
        const val colorPaletteInkDim: Argb = 0x6BECE8E4L
        const val colorPaletteInkFaint: Argb = 0x2EECE8E4L
        const val colorPaletteAccentViolet: Argb = 0xFF8E7BFFL
        const val colorPaletteAccentVioletBright: Argb = 0xFFA593FFL
        const val colorPaletteAccentVioletDeep: Argb = 0xFF7867E6L
        const val colorPaletteProvenanceNative: Argb = 0xFFC7EF9EL
        const val colorPaletteProvenanceCloud: Argb = 0xFF35E0FFL
        const val colorPaletteHairlineDefault: Argb = 0x14FFFFFFL
        const val colorPaletteHairlineStrong: Argb = 0x24FFFFFFL
        const val colorPaletteGlassPane: Argb = 0x850A0809L
        const val colorPaletteSignalDanger: Argb = 0xFFE5564BL
        const val colorPaletteSignalWarning: Argb = 0xFFE0941AL
        const val colorPaletteSignalSuccess: Argb = 0xFF5BBF7AL
        const val colorPaletteMaterialStone: Argb = 0xFF9B958CL
        const val colorPaletteMaterialSmog: Argb = 0xFFCC1A0AL
        const val colorPaletteMaterialLight: Argb = 0xFFFFD2B0L
        const val colorTextPrimary: Argb = 0xEBECE8E4L
        const val colorTextSecondary: Argb = 0x6BECE8E4L
        const val colorTextFaint: Argb = 0x2EECE8E4L
        const val colorTextInverse: Argb = 0xFF0A0809L
        const val colorTextAccent: Argb = 0xFF8E7BFFL
        const val colorBackgroundField: Argb = 0xFF000000L
        const val colorBackgroundSurface: Argb = 0xFF121212L
        const val colorBackgroundGlass: Argb = 0x850A0809L
        const val colorBackgroundInverse: Argb = 0xFFECE8E4L
        const val colorBorderHairline: Argb = 0x14FFFFFFL
        const val colorBorderStrong: Argb = 0x24FFFFFFL
        const val colorBorderFocus: Argb = 0xFF8E7BFFL
        const val colorActionPrimary: Argb = 0xFF8E7BFFL
        const val colorActionPrimaryHover: Argb = 0xFFA593FFL
        const val colorActionPrimaryActive: Argb = 0xFF7867E6L
        const val colorActionOnPrimary: Argb = 0xFF0A0809L
        const val colorProvenanceNative: Argb = 0xFFC7EF9EL
        const val colorProvenanceCloud: Argb = 0xFF35E0FFL
        const val colorFeedbackDanger: Argb = 0xFFE5564BL
        const val colorFeedbackWarning: Argb = 0xFFE0941AL
        const val colorFeedbackSuccess: Argb = 0xFF5BBF7AL
        const val controlSurface: Argb = 0xFF16161AL
        const val controlSurfaceRaised: Argb = 0xFF212128L
        const val controlSurfaceHigh: Argb = 0xFF2C2C34L
        const val controlGroove: Argb = 0xFF050506L
        const val controlEdge: Argb = 0xFF3A3A44L
        const val controlRim: Argb = 0x29FFFFFFL
        const val controlRimSoft: Argb = 0x17FFFFFFL
        const val controlIndicator: Argb = 0xFF6B6760L
        const val controlScreen: Argb = 0xFF141210L
        const val controlScreenInk: Argb = 0xFFDDDBD6L
        const val controlScreenDim: Argb = 0xFF5C5A56L
    }

    /** Dimensions, in density-independent pixels (dp; type scale is sp). */
    object Dimension {
        const val spacing0: Int = 0
        const val spacing1: Int = 4
        const val spacing2: Int = 8
        const val spacing3: Int = 12
        const val spacing4: Int = 16
        const val spacing5: Int = 20
        const val spacing6: Int = 24
        const val spacing8: Int = 32
        const val spacing10: Int = 40
        const val spacing12: Int = 48
        const val spacing16: Int = 64
        const val radiusNone: Int = 0
        const val radiusSm: Int = 4
        const val radiusMd: Int = 8
        const val radiusLg: Int = 12
        const val radiusXl: Int = 16
        const val radiusFull: Int = 9999
        const val sizeControlSm: Int = 32
        const val sizeControlMd: Int = 40
        const val sizeControlLg: Int = 48
        const val sizeBorderThin: Int = 1
        const val sizeBorderThick: Int = 2
        const val fontSizeMicro: Int = 10
        const val fontSizeLabel: Int = 11
        const val fontSizeXs: Int = 12
        const val fontSizeSm: Int = 14
        const val fontSizeMd: Int = 16
        const val fontSizeLg: Int = 18
        const val fontSizeXl: Int = 20
        const val fontSize2xl: Int = 24
        const val fontSize3xl: Int = 32
    }

    /** Durations, in milliseconds. */
    object Duration {
        const val durationInstant: Int = 120
        const val durationCalm: Int = 300
        const val durationPane: Int = 420
    }
}
