package xyz.mdhv.asom.lab.bench

import java.security.MessageDigest

/** Why a run was refused or stopped (benchmark.md 11.2 reason codes and 6.4 / 11.3 abort reasons). */
enum class PreflightReason {
    NO_ENGINE, MODELS_MISSING, STORAGE, TOO_WARM, POWER_SAVER, NEEDS_CHARGER, BATTERY_LOW, BATTERY_WARM, DEVICE_BUSY, SERVING,
    NOT_FOREGROUND, NOT_ENOUGH_MEMORY, VIRTUALIZED, NO_THERMAL_SIGNAL,
}

class ConsentError(message: String) : IllegalStateException(message)

/**
 * The consent sheet: the exact words shown (benchmark.md 11.1), generated by the core. The UI's Start action must submit the
 * SHA-256 of the text it displayed; that is the only way to mint a [ConsentToken] (rule B5). The text is a pure function of its inputs.
 */
class ConsentSheet private constructor(val plan: RunPlan, val text: String) {
    val textSha256: ByteArray = MessageDigest.getInstance("SHA-256").digest(text.toByteArray(Charsets.UTF_8))

    /** Throws [ConsentError] unless [shownTextSha256] is the hash of [text]. A token is valid for 5 minutes and covers exactly one run. */
    fun confirm(shownTextSha256: ByteArray, nowMs: Long): ConsentToken {
        if (!MessageDigest.isEqual(shownTextSha256, textSha256)) throw ConsentError("the hash does not match the text that was shown")
        return ConsentToken(plan.plan, nowMs)
    }

    companion object {
        const val TOKEN_TTL_MS: Long = 300_000L

        /** [downloadBytes] is the total of the files still to download (0 when all are present); [tiers] names them. */
        fun forPlan(plan: RunPlan, downloadBytes: Long, tiers: List<String>, t3OptInOffered: Boolean, sustainedToday: Boolean): ConsentSheet {
            val minutes = when (plan.plan) {
                "quick" -> "up to 5"
                "standard" -> "20-30"
                else -> "a few"
            }
            val gb = if (downloadBytes == 0L) "0.0" else TextRender.gb(downloadBytes).removeSuffix(" GB")
            val lines = mutableListOf<String>()
            lines += "Run the ${plan.plan} device test?"
            lines += "- Takes about $minutes minutes. You can stop at any time."
            if (plan.sustain != null) {
                lines += "- Makes the device warm and uses power. Keep it on its charger."
            } else {
                lines += "- Uses power for a few minutes."
            }
            lines += if (downloadBytes == 0L) "- Downloads nothing: the test models are already on this device." else "- Downloads $gb GB of test models over Wi-Fi first (${tiers.joinToString(", ")})."
            if (t3OptInOffered) lines += "  [ ] Also test 8B models (+5.0 GB). Without this, 8B speed is estimated."
            lines += "- Nothing is uploaded. Results stay on this device unless you share them."
            lines += "- If the device gets too hot, the test stops by itself."
            if (sustainedToday) lines += "  [ ] Run the heat test again today."
            lines += "[Not now]   [Start]"
            return ConsentSheet(plan, lines.joinToString("\n") + "\n")
        }
    }
}

/** Covers exactly one run of [planId]; expires [ConsentSheet.TOKEN_TTL_MS] after minting; single use. */
class ConsentToken internal constructor(val planId: String, val mintedAtMs: Long) {
    var consumed: Boolean = false
        private set

    val expiresAtMs: Long get() = mintedAtMs + ConsentSheet.TOKEN_TTL_MS

    fun consume(planId: String, nowMs: Long) {
        if (consumed) throw ConsentError("token already used")
        if (planId != this.planId) throw ConsentError("token is for plan ${this.planId}")
        if (nowMs >= expiresAtMs) throw ConsentError("token expired")
        consumed = true
    }
}
